@startuml

state AntennaDeployment
      AntennaDeployment : Deploy antenna
      AntennaDeployment : Verify deployment

state SafeHold
      SafeHold : Transmit SeaLion Beacon 
state ADOS 
      ADOS : Compute Spacecraft Attitude
      ADOS : Compute Orbit position
      ADOS : Compute Timetable and Switch Mode
state QueryReceiver
      QueryReceiver : GroundCommand
state Comms
      Comms : Read Memory
      Comms : Downlink Telemetry 

state MissionMode1
      MissionMode1 : Query Impedence probe and Multi-Spectral sensor
state MissionMode2
      MissionMode2 : 
[*] --> AntennaDeployment : EPS & CDS \n Powered on \n 45 min delay
AntennaDeployment --> SafeHold
Comms --> ADOS
SafeHold --> QueryReceiver
QueryReceiver --> Comms : Ground Interrupt?
QueryReceiver --> ADOS : No ground Interput
ADOS --> MissionMode1 : Time for MM1?
ADOS --> MissionMode2 : Time for MM2?
MissionMode1 --> SafeHold
MissionMode2 --> SafeHold
@enduml

@startuml
[*] --> Active

state Active {
state AntennaDeployment
      AntennaDeployment : Deploy antenna
      AntennaDeployment : Verify deployment

state SafeHold
      SafeHold : Transmit SeaLion Beacon 

state QueryReceiver
      QueryReceiver : GroundCommand
state Comms
      Comms : Read Memory
      Comms : Downlink Telemetry 

state MissionMode1
      MissionMode1 : Query Impedence probe and Multi-Spectral sensor
state MissionMode2
      MissionMode2 : 
[*] --> AntennaDeployment : EPS & CDS \n Powered on \n 45 min delay
AntennaDeployment --> SafeHold

SafeHold --> QueryReceiver
QueryReceiver --> Comms : Ground Interrupt?

MissionMode1 --> SafeHold
MissionMode2 --> SafeHold
   
  ||
  [*] -> ADOS
  state ADOS 
      ADOS : Compute Spacecraft Attitude
      ADOS : Compute Orbit position
      ADOS : Compute Timetable and Switch Mode
  
}
@enduml