@startuml

state AntennaDeployment
      AntennaDeployment : Deploy antenna
      AntennaDeployment : Verify deployment
state SafeHold
      SafeHold : Transmit SeaLion Beacon 
state QueryReceiver
      QueryReceiver : Check for GroundCommand
state Comms
      Comms : Read Memory
      Comms : Downlink Telemetry 
state Timer
      Timer : Check if last computed OrbitPropagator time was 1s or more
      Timer : Check if last computed GPSreceiver time was 10mins or more
state MissionMode1
      MissionMode1 : Collect and Store Impedence probe and Multi-Spectral sensor data 
state MissionMode2
      MissionMode2 : Turn on current supply for 2-minutes to burnwire mechanism 
      MissionMode2 : Log DeCS deployment event 
state ProcessScheduler
      ProcessScheduler : Perform Scheduled Task
state OrbitPropagator 
      OrbitalPropagator : Compute Spacecraft Attitude
      OrbitPropagator : Compute Orbit position
      OrbitPropagator : Compute Timetable
state GPSreceiver 
      GPSreceiver : Ping GPS

[*] --> AntennaDeployment : EPS & CDS \n Powered on \n 45 min delay
AntennaDeployment --> SafeHold
SafeHold --> QueryReceiver
QueryReceiver --> Comms : Ground Interrupt?
QueryReceiver --> Timer : No ground Interrupt
Comms --> Timer
MissionMode1 --> SafeHold
MissionMode2 --> SafeHold
ProcessScheduler --> SafeHold
ProcessScheduler --> MissionMode1 
ProcessScheduler --> MissionMode2 
OrbitPropagator --> ProcessScheduler
Timer  --> OrbitPropagator : delta_time_GPS < 10 mins
Timer --> GPSreceiver : delta_time_GPS >= 10 mins
GPSreceiver --> OrbitPropagator
@enduml